[project]
name = "progress-watchdog"
version = "0.1.0"
description = "Progress Watchdog is a Python package that helps you avoid staying stuck or getting tunnel vision while time flows by."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playsound>=1.3.0",
    "pynput>=1.8.0",
]
