[project]
name = "watchdog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "loguru>=0.7.3",
    "playsound>=1.3.0",
]
