[project]
name = "watchdog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playsound>=1.3.0",
    "pynput>=1.8.0",
]
